### ISSUE TITLE
Invert colors for Night Mode

### ISSUE THREAD

**Issue by tjbenator** [dschep/proven#10]
Requesting inverted colors for Night Mode :smiley: 

![selection_177](https://user-images.githubusercontent.com/1761657/32877498-ae05777a-ca56-11e7-9aae-a849e83248be.png)

![Night Mode](https://user-images.githubusercontent.com/1761657/32877526-ced170da-ca56-11e7-92e9-3c9c1e54738c.png)

**Comment by dschep** [comment]
Done in v1.1
![screenshot from 2017-11-16 22-08-46](https://user-images.githubusercontent.com/667763/32927474-c19d703e-cb1a-11e7-942c-023dc786d728.png)
