### ISSUE TITLE
Linked In Support?

### ISSUE THREAD

**Issue by JonTheNiceGuy** [dschep/proven#27]
It would be great if we could extend this to cover the Linked In site? I've also seen some other sites you've started to build support for (#5, #4, #3)... anything I can do to help with those?

If I wanted to help by building support in for those platforms, would it just be a matter of duplicating the code you've created (e.g. [reddit support - issue 3](https://github.com/dschep/proven/commit/fcde336590ebd23fa69115c5fed9f931af18826d)) to support the target platform of choice?

**Comment by dschep** [comment]
That's dependent on keybase supporting linkedin. That is easier now that they've implemented a more generic proof system, but it doesn't seem to be supported yet, so this plugin can't either

**Comment by JonTheNiceGuy** [comment]
Ah, good point well made. Thanks for getting back to me!

**Comment by dschep** [comment]
gonna close this since I don't really expect it to be added soon. And if it is added, the unreleased rework in progress will add support for generic sites anyway, so it should be supported were it to be added by keybase
