### ISSUE TITLE
Mastodon proof icon needed!

### ISSUE THREAD

**Issue by levisan** [dschep/proven#29]
If you look at a Twitter profile of someone who has verified a Mastodon identity (such as https://twitter.com/maxtaco), where a lovely Mastodon icon could go, there's just "undefined"
![Screenshot_2019-04-16 Max Krohn ( maxtaco) on Twitter](https://user-images.githubusercontent.com/1847670/56238128-ef4a9680-604a-11e9-8c3c-49558d1ec40f.png)

**Comment by dschep** [comment]
Partially implemented in #30, but not released yet bc I realized it doesn't work on firefox. in progress tho. track #31 for progress on that.
